version: '3.9'

services:
  app:
    build:
      context: .
      args:
        - DEV="True"
    command: >
      sh -c "python manage.py migrate &&
             gunicorn app.wsgi:application --bind 0.0.0.0:8000 --reload"
    expose:
      - 8000
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    env_file:
      - ./env/dev/.django
    depends_on:
      - db

  db:
    image: postgres
    env_file:
      - ./env/dev/.postgres
    volumes:
      - dev-db-data:/var/lib/postgres/data
    ports:
      - "54320:5432"

volumes:
  dev-db-data: